# NOTE: You need to build your image and rewrite image property (and others)

version: '2.0'

services:
  meteorexample:
    container_name: meteorexample-1
    hostname: meteor.click
    restart: always
    image: martinezko/baseimage-meteor-example:latest
    ports:
      - 127.0.0.1:3000:80
    environment:
      APP: meteorexample
      ROOT_URL: http://meteor.click/
      MONGO_URL: mongodb://USERNAME:PASSWORD@172.17.0.1:27017/DATABASE
      MONGO_OPLOG_URL: mongodb://USERNAME:PASSWORD@mongo:27017/local
      MAIL_URL: smtps://info@meteor.click:PASSWORD@mail.server.net:465/
      NODE_ENV: production
      PORT: 80
      METEOR_SETTINGS: '{}' # paste meteor settings.json here in one line!
    volumes:
      - ./log:/var/log
