FROM martinezko/baseimage-meteor
MAINTAINER Martin Bucko <bucko@treecom.net>

# For overwriting environment variables (if you don't use docker-compose file)
# ENV
# 	APP: meteorexample \
# 	ROOT_URL: http://meteor.click/ \
# 	PORT: 3000 \
# 	MONGO_URL: mongodb://USERNAME:PASSWORD@mongodb:27017/DATABASE \
# 	MONGO_OPLOG_URL: mongodb://USERNAME:PASSWORD@mongodb:27017/local \
# 	MAIL_URL: smtps://example@meteor.click:PASSWORD@mail.server.net:465/ \
# 	NODE_ENV: production \
# 	METEOR_SETTINGS: '{}'

# VOLUME /var/log/meteor.log

# Expose port
EXPOSE 3000/tcp
