FROM martinezko/baseimage-meteor
MAINTAINER Martin Bucko <bucko@treecom.net>

# For overwriting environment variables (if you don't use docker-compose file)

# ENV
# 	APP: meteorexample \
# 	ROOT_URL: http://meteor.click/ \
# 	PORT: 80 \
# 	MONGO_URL: mongodb://USERNAME:PASSWORD@172.17.0.1:27017/DATABASE \
# 	MONGO_OPLOG_URL: mongodb://USERNAME:PASSWORD@mongo:27017/local \
# 	MAIL_URL: smtps://info@meteor.click:PASSWORD@mail.server.net:465/ \
# 	NODE_ENV: production \
# 	METEOR_SETTINGS: '{}'

# EXPOSE 80

